    spring.application.name=demo

    spring.datasource.url=jdbc:mysql://localhost:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    spring.datasource.username=root
    spring.datasource.password=akshay@282005
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.defer-datasource-initialization=true
    spring.sql.init.mode=never

    jwt.secret=d2VsbG5lc3MtbWFya2V0cGxhY2Utc2VjcmV0LWtlLWZvci1qd3QtYXV0aGVudGljYXRpb24tMjAyNi1zZWN1cmUta2V5
    jwt.access-token.expiration=900000
    jwt.refresh-token.expiration=604800000

    npi.api.base-url=https://npiregistry.cms.hhs.gov/api/

    spring.mail.host=smtp.gmail.com
    spring.mail.port=587
    spring.mail.username=wellnessapp246@gmail.com
    spring.mail.password=gxnsmvychgkhrxxk
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.starttls.enable=true
    spring.mail.properties.mail.smtp.starttls.required=true

    app.reminder.hours-before=24
    app.reminder.cron=0 0 * * * *

    server.port=8084